<%
'   ASP Resources Http://www.asp-dev.ml.org 
'   Version 1.2.1
'
ConnString = "Provider=Microsoft.Jet.OLEDB.4.0; Data Source=" & Server.MapPath("ubbs.mdb") & ";"

BBEmail = "leandro@towebs.com"

BBTitle = "ASP Resources Forums"

BadWordFiler = "true"   '  True / False To use filter

Smiles = "true"  '  True/False to use Smiles

ICQ = "true" '   True/False to use ICQ Graphics

PageBGColor = "white"

TitleImgLocation = "bboard.jpg"

DefaultFontFace = "Verdana, Arial, Helvetica"
DefaultFontColor = "#000080"

LinkColor = "#000080"
LinkTextDecoration = "underline"

VisitedLinkColor = "#008080"
VisitedTextDecoration = "underline"

ActiveLinkColor = "red"

HoverFontColor = "red"
HoverTextDecoration = "underline"

HeadCellColor="#0000A0"
HeadFontColor = "#ffffff"

CategoryCellColor="#8080FF"
CategoryFontColor="#f7f7f7"

ForumCellColor = "#f7f7f7"
AltForumCellColor = "#e1e1e1"

ForumFontColor = "#000080"
ForumLinkColor = "#000080"

NewFontColor = "#ff0000"

BadWords = "fuck|wank|shit"

%>