<body bgcolor="#FFFFFF" text="#000000" link="#000000" vlink="#000000" alink="#000000">
<%

ConnString = "Provider=Microsoft.Jet.OLEDB.4.0; Data Source=" & Server.MapPath("./admin/ubbs.mdb") & ";"

BBEmail = "leandro@towebs.com"

BBTitle = "Foro ToWebs"

BadWordFiler = "true"   '  True / False To use filter

Smiles = "true"  '  True/False to use Smiles

ICQ = "true" '   True/False to use ICQ Graphics

PageBGColor = "white"

TitleImgLocation = "bboard.jpg"

DefaultFontFace = "Verdana, Arial, Helvetica"
DefaultFontColor = "#000000"

LinkColor = "#000000"
LinkTextDecoration = "underline"

VisitedLinkColor = "Red"
VisitedTextDecoration = "underline"

ActiveLinkColor = "red"

HoverFontColor = "red"
HoverTextDecoration = "underline"

HeadCellColor="#800000"
HeadFontColor = "#FFFFFF"

CategoryCellColor="#AF0201"
CategoryFontColor="#f7f7f7"

ForumCellColor = "#CCCCCC"
AltForumCellColor = "#e1e1e1"

ForumFontColor = "#000000"
ForumLinkColor = "RED"

NewFontColor = "#ff0000"

BadWords = "fuck|wank|shit"

%>